spring:
  application:
    name: zfiles

server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: local

zfiles:
  cdn-type: gcp
  max-filesize-mb: 10

local:
  prefix-http-url: http://localhost
  prefix-upload: /Users/madan/Documents/JayaMeen/www/files

gcp:
  prefix-http-url: https://storage.googleapis.com
  prefix-upload:
  project-id: ${GCP_PROJECT_ID}
  bucket-id: ${GCP_BUCKET_ID}
  upload-url: https://storage.googleapis.com
  config-data: ${GCP_CONFIG_DATA_KEY}

aws:
  prefix-http-url: http://localhost
  prefix-upload:

digitalocean:
  prefix-http-url: http://localhost
  prefix-upload:
  spaces:
    upload-url: https://sgp1.digitaloceanspaces.com
    prefix-url: https://uxin.sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: uxin
    dokey: ${DO_KEY:test}
    dosecret: ${DO_SECRET:test}
