spring:
  application:
    name: zfiles

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: local-digitalocean

zfiles:
  cdn-type: local
  max-filesize-mb: 10

local:
  prefix-fetch: http://localhost
  prefix-upload: /Users/madan/Documents/JayaMeen/www/files

digitalocean:
  spaces:
    upload-url: https://sgp1.digitaloceanspaces.com
    prefix-url: https://uxin.sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: uxin
    dokey: ${DO_KEY:test}
    dosecret: ${DO_SECRET:test}

gcp:
  project:
    id: ${GCP_PROJECT_ID}
  bucket:
    id: ${GCP_BUCKET_ID}
  url: https://storage.googleapis.com/
  config-data: ${GCP_CONFIG_DATA_KEY}
